export const properties: PropertyType[] = ['character', 'location', 'episode'];
export const statuses: StatusType[] = ['alive', 'dead', 'unknown'];
export const genders: GenderType[] = [
  'female',
  'male',
  'genderless',
  'unknown',
];
export const specieses: SpeciesTypes[] = [
  'Alien',
  'Animal',
  'Cronenberg',
  'Disease',
  'Human',
  'Humanoid',
  'Mythological Creature',
  'Poopybutthole',
  'Robot',
  'unknown',
];

export const locationTypes: LocationType[] = [
  'Artificially generated world',
  'Acid Plant',
  'Asteroid',
  'Base',
  'Cluster',
  'Convention',
  'Consciousness',
  'Customs',
  'Daycare',
  'Dream',
  'Dimension',
  'Death Star',
  'Diegesis',
  'Dwarf planet (Celestial Dwarf)',
  'Fantasy town',
  'Game',
  'Hell',
  'Liquid',
  'Menagerie',
  'Memory',
  'Microverse',
  'Miniverse',
  'Mount',
  'Nightmare',
  'Non-Diegetic Alternative Reality',
  'Planet',
  'Quadrant',
  'Quasar',
  'Police Department',
  'Resort',
  'Spa',
  'Space station',
  'Space',
  'Spacecraft',
  'Teenyverse',
  'TV',
  'unknown',
];
