type LocationType =
  | 'Artificially generated world'
  | 'Acid Plant'
  | 'Asteroid'
  | 'Base'
  | 'Cluster'
  | 'Convention'
  | 'Consciousness'
  | 'Customs'
  | 'Daycare'
  | 'Dream'
  | 'Dimension'
  | 'Death Star'
  | 'Diegesis'
  | 'Dwarf planet (Celestial Dwarf)'
  | 'Fantasy town'
  | 'Game'
  | 'Hell'
  | 'Liquid'
  | 'Menagerie'
  | 'Memory'
  | 'Microverse'
  | 'Miniverse'
  | 'Mount'
  | 'Nightmare'
  | 'Non-Diegetic Alternative Reality'
  | 'Planet'
  | 'Quadrant'
  | 'Quasar'
  | 'Police Department'
  | 'Resort'
  | 'Spa'
  | 'Space station'
  | 'Space'
  | 'Spacecraft'
  | 'Teenyverse'
  | 'TV'
  | 'unknown';
